### ISSUE TITLE
what is first_VR_ranklist_path, where I can find it?

### ISSUE THREAD

**Issue by freeman-1995** [houzhijian/CONQUER#2]

**Comment by houzhijian** [comment]
Hi, sorry for the late response.

First_VR_ranklist_path means the filename path to store the video retrieval rank list provided by the first-stage model, i.e., HERO. 

If you download this file [tvr_feature_release.tar.gz](https://drive.google.com/file/d/1DFnMNH-oi6-cZbl1coXqa_KjtsIsObxG/view?usp=sharing) (21GB), you will find the file in the data directory.
