### ISSUE TITLE
Model config for training on DiDeMo

### ISSUE THREAD

**Issue by Aarontncl** [houzhijian/CONQUER#5]
Hi, zhijian

Thanks for your great work and code! I notice the provided config files don't include the model config for training on DiDeMo, and the command lines for this dataset also seem to be missing. Could you please share all these original configurations to make experiments on DiDeMo dataset more accessible? Thanks again!

**Comment by zhanglong-ustc** [comment]
Hi, zhijian

Thanks for your great work and code! I notice the provided config files don't include the model config for training on DiDeMo, and the command lines for this dataset also seem to be missing. Could you please share all these original configurations to make experiments on DiDeMo dataset more accessible? Thanks again!
